kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-only-ingress-to-workload
  namespace: a0008
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: aspnetapp
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik-ingress-ilb
          app.kubernetes.io/instance: traefik-ingress-ilb
