apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
commonAnnotations:
  region: "1"
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: flux
    namespace: cluster-baseline-settings
  path: regionalize-flux-git-path.yaml
